# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: building and deploying image
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: testimagepaxafe.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: 
          docker build . -t testimagepaxafe.azurecr.io/myapp:${{ github.sha}}
          docker push testimagepaxafe.azurecr.io/myapp:${{ github.sha}}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az containerapp update \
            --name <container-app-internal> \
            --resource-group <test-resource> \
            --image testimagepaxafe.azurecr.io/myapp:${{ github.sha}} \
            --registry-server testimagepaxafe.azurecr.io \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }}
